cShareSystems.load_pas("Dreadnought Map Pack", [
        "coui://ui/mods/dreadnought/systems/1v1_Blitz_Botchi_1.1.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Blitz_Firage_1.1.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Blitz_Heatstroke_1.3.pas",

        "coui://ui/mods/dreadnought/systems/1v1_Anvil_1.1.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Archon_1.2.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Atlas-Station_1.2.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Atomic_1.2.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Atomic_LE_2.2.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Avalanche_1.9.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Avalanche_LE_1.9.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Brittle_1.3.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Climber_1.2.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Crackle_1.3.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Crakatone_1.2.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Crest_1.3.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Crux_1.2.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Eye-of-Eternity_1.6.pas",
        "coui://ui/mods/dreadnought/systems/FFA_Eye-of-Eternity_1.6.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Forganic_1.0.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Foundry_1.4.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Freezer_1.2.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Frosjir_1.0.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Garden_1.4.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Hush_1.2.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Icebreaker_1.3.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Ice-cream_1.0.pas",

        "coui://ui/mods/dreadnought/systems/1v1_Jongleur_1.3.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Kazranaut_2.8.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Kolpher_1.8.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Molg_1.3.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Nastolda_2.0.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Oasis_1.1.pas", "coui://ui/mods/dreadnought/systems/1v1_Odium_1.4.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Paranoid-Android_1.2.pas",
		"coui://ui/mods/dreadnought/systems/1v1_Primarden_1.1.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Pummel_1.0.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Pummel_1.1.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Smoker_1.4.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Station_53C_2.6.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Temple-of-the-Monkey-God_2.4.pas",
        "coui://ui/mods/dreadnought/systems/1v1_Tz-5_1.2.pas",

        "coui://ui/mods/dreadnought/systems/1v1-2v2_Acraphon_1.6.pas",
        "coui://ui/mods/dreadnought/systems/1v1-2v2_Ignitus_1.3.pas",
        "coui://ui/mods/dreadnought/systems/1v1-2v2_Mion-9_1.1.pas",
        "coui://ui/mods/dreadnought/systems/1v1-2v2_Heartbreak-Ridge_2.0.pas",
        "coui://ui/mods/dreadnought/systems/1v1-2v2_Burning-Oasis_1.5.pas",
        "coui://ui/mods/dreadnought/systems/1v1-2v2_Snapper_1.4.pas",

        "coui://ui/mods/dreadnought/systems/1v1-3v3_Drinker_1.5.pas",
        "coui://ui/mods/dreadnought/systems/1v1-3v3_Rustad_1.25.pas",
        "coui://ui/mods/dreadnought/systems/1v1-3v3_yukon-ho_3.3.pas",
		
		"coui://ui/mods/dreadnought/systems/3v3_Midget_Planet_1.0.pas",

        "coui://ui/mods/dreadnought/systems/4v4_Sabbath-Station_1.0.pas",
        "coui://ui/mods/dreadnought/systems/4v4_Psycho_1.1.pas",

        "coui://ui/mods/dreadnought/systems/5v5_Oculan-Mining-Facility_1.1.pas",
        "coui://ui/mods/dreadnought/systems/5v5_TNT_1.2.pas",

        "coui://ui/mods/dreadnought/systems/Cyclonus-X_1v1_1.3.pas",
        "coui://ui/mods/dreadnought/systems/Cyclonus-X_2v2_1.3.pas",
        "coui://ui/mods/dreadnought/systems/Cyclonus-X_3v3_1.3.pas",
        "coui://ui/mods/dreadnought/systems/Cyclonus-X_4v4_Standard_1.3.pas",
        "coui://ui/mods/dreadnought/systems/Cyclonus-X_4v4_Orbital_1.3.pas",
        "coui://ui/mods/dreadnought/systems/Cyclonus-X_5v5_Standard_1.3.pas",
        "coui://ui/mods/dreadnought/systems/Cyclonus-X_5v5_Brawl_1.3.pas",

        "coui://ui/mods/dreadnought/systems/11v11_Aquamax_1.0.pas",
        "coui://ui/mods/dreadnought/systems/16v16_Aquamax_1.0.pas",
        "coui://ui/mods/dreadnought/systems/16v16_SUPER_Aquamax_1.2.6.pas",
        "coui://ui/mods/dreadnought/systems/RokNok_1v1_1.0.pas", "coui://ui/mods/dreadnought/systems/Uztek_1v1-2v2_1.0.pas",
        "coui://ui/mods/dreadnought/systems/BabyEarth.pas"

    ]);
